config/routes.rb
Rails.application.routes.draw do
  resources :shopping_notes
  resources :customers
  resources :orders
  resources :shopping_items
  resources :shopping_bags
  resources :pages
  resources :dreamtypes
  resources :products
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  
  get '/about', to: 'pages#about', as: 'about'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/register', to: 'customers#register', as: 'register'
  get '/outstanding_orders', to: 'customers#outstanding', as: 'outstanding'
  get '/logout', to: 'customers#logout', as: 'logout'
  get '/checkout', to: 'shopping_bags#checkout', as: 'checkout'
  get '/login', to: 'customers#login', as: 'login'
  post '/register', to: 'customers#register', as: 'register_post'
  post '/login', to: 'customers#login', as: 'login_post'
  post '/logout', to: 'customers#logout', as: 'logout_post'
  post '/checkout', to: 'shopping_bags#checkout', as: 'checkout_post'


  root to: 'products#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product, :class_name => "Product", :foreign_key => "products_id"
  belongs_to :cart
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_one_attached :personal_photo
	belongs_to :province, :class_name => "Province", :foreign_key => "provinces_id"

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true
	
	#fix this later...
	#canadian_postal_code = /\A[ABCEGHJKLMNPRSTVXY]{1}\\d{1}[A-Z]{1}[ -]?\\d{1}[A-Z]{1}\\d{1}\z/
	#validates :postal_code, format: { with: canadian_postal_code }
end

app/models/dreamtype.rb
class Dreamtype < ApplicationRecord

	has_many :products
	validates :horror_rating, numericality: { less_than_or_equal_to: 10,  only_integer: true }
	validates :dreamtype, presence: true

	def display_name 
		dreamtype
	end
end

app/models/order.rb
class Order < ApplicationRecord
belongs_to :customer, :class_name => "Customer", :foreign_key => "customers_id"
validates :order_date, presence: true
before_create :set_order_date
before_save :set_fulfilled 
has_many :order_details
end

def set_order_date
	self.order_date = Date.today
end

def set_fulfilled
	if self.paid_date?
		self.fulfilled = true
	end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, presence: true
  validates :product_price, presence: true
  validates :total, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
	has_one_attached :about_photo
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :dreamtype
  has_many :order_details

   mount_uploader :image, ImageUploader

  validates :description, presence: true
  validates :name, presence: true
  validates :stock, presence: true
  validates :price_per_unit, presence: true

  paginates_per 4

end

app/models/province.rb
class Province < ApplicationRecord
	has_many :customers

	validates :code, presence: true
end

app/models/shopping_bag.rb
class ShoppingBag < ApplicationRecord
  has_many :shopping_items
  
  def add_product(product_params)
    current_item = shopping_items.find_by(products_id: product_params[:product][:products_id])

    if current_item
      current_item.quantity += product_params[:product][:quantity].to_i
      current_item.save
    else
      new_item = shopping_items.create(products_id: product_params[:product][:products_id], 
                                  quantity: product_params[:product][:quantity],
                                  shopping_bag_id: self.id)
    end
      new_item
  end

  def bag_size
    size = 0
    self.shopping_items.each do |item|
      size += item.quantity
    end
    size
  end

  def total_price
    shopping_items.to_a.sum { |item| item.product.price_per_unit * item.quantity }
  end
end

app/models/shopping_item.rb
class ShoppingItem < ApplicationRecord
  belongs_to :product, :class_name => "Product", :foreign_key => "products_id"
  belongs_to :shopping_bag
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/shopping_bags_controller.rb
class ShoppingBagsController < ApplicationController
	before_action :set_bag, only: [:index]

	def checkout
		@customer = Customer.where(id: session[:customer_id]).first

		@taxes = @customer.province.gst + @customer.province.pst + @customer.province.hst
		@total_cost = (current_bag.total_price * @taxes) + current_bag.total_price

		if params[:tax_total]
			@order = Order.create(order_date: Date.today, pst: @customer.province.pst,
				gst: @customer.province.gst, hst: @customer.province.hst, customers_id: @customer.id,
				total: @total_cost, 
				fulfilled: false)

			@order.save

			current_bag.shopping_items.each do |item|

				@total_cost = item.product.price_per_unit * item.quantity

				@order_detail = OrderDetail.create(
					quantity: item.quantity, discount: item.product.discount, 
					product_price: item.product.price_per_unit,
					order_id: @order.id, product_id: item.product.id,
					total: @total_cost)

				@order_detail.save
			end

			@errors = @order.errors.full_messages

			if @order.valid?
				redirect_to products_path
			end

		end

	end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dreamtypes_helper.rb
module DreamtypesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shopping_bags_helper.rb
module ShoppingBagsHelper
end

app/views/shopping_bags/checkout.html.erb
<p>Order Details</p>

<%= form_for shopping_bags_url, :url => checkout_post_url, :html => { :method => :post } do %>
<div>
<%= @customer.first_name %>
</div>
<div>
<%= @customer.address %>
</div>
<div>
<%= @customer.province.gst %>
</div>
<div>
<%= @customer.province.hst %>
</div>
<div>
<%= @customer.province.pst %>
</div>

<div>
<%= @customer.province.pst %>
</div>

 <% current_bag.shopping_items.each do |item| %>
 <%= item.product.name %>
  <%= item.quantity %>
   <%= item.product.price_per_unit %>
   <% end %>

<div>
   Cart Total Before Tax: <%= number_to_currency(current_bag.total_price) %>
</div>

<div>
	 <input name="tax_total" type="hidden" value="<%= @total_cost %>" />
   Cart Total With Tax: <%= number_to_currency(@total_cost) %>
</div>

<% if @errors %>
<% @errors.each do |msg| %>
      <p class = "red"><%= msg %></p>
   <% end %>
<% end %>

<%= submit_tag 'PLACE ORDER', name: nil, class: "btn btn-light" %>
<% end %>

app/views/shopping_bags/index.html.erb
 <% if current_bag.total_price != 0 %>
 <% current_bag.shopping_items.each do |item| %>
  <div id="container">
 <h2>Product Name: <%= item.product.name %></h2>
 <h3>Quantity: <%= item.quantity %></h3>
 <div id ="edit">

 	<%= form_for item, :method => :PUT do |f| %>
 	<%= f.number_field :quantity, value: item.quantity, min: 1 %>
 	<%= f.submit "UPDATE" %>
 	<% end %>

 	<%= form_for item, :method => :DELETE do |f| %>
 	<%= f.submit "DELETE" %>
 	<% end %>
 </div>
 <% end %>
</div>
<h4>Cart Total Before Tax: <%= number_to_currency(current_bag.total_price) %></h4>


 <% if !session[:customer_id].nil? %>
<%= link_to "CHECKOUT", checkout_path %>
<% else %>
<%= link_to "LOGIN TO COMPELTE PURCHASE", login_url %>
<% end %>


<% else %>
<h1>Your Shopping Bag is Empty.</h1>
<% end %>