config/routes.rb
Rails.application.routes.draw do
  resources :shopping_notes
  resources :customers
  resources :orders
  resources :shopping_items
  resources :shopping_bags
  resources :pages
  resources :dreamtypes
  resources :products
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  
  get '/about', to: 'pages#about', as: 'about'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/register', to: 'customers#register', as: 'register'
  get '/outstanding_orders', to: 'customers#outstanding', as: 'outstanding'
  get '/logout', to: 'customers#logout', as: 'logout'
  get '/checkout', to: 'shopping_bags#checkout', as: 'checkout'
  get '/login', to: 'customers#login', as: 'login'
  post '/register', to: 'customers#register', as: 'register_post'
  post '/login', to: 'customers#login', as: 'login_post'
  post '/logout', to: 'customers#logout', as: 'logout_post'
  post '/checkout', to: 'shopping_bags#checkout', as: 'checkout_post'


  root to: 'products#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product, :class_name => "Product", :foreign_key => "products_id"
  belongs_to :cart
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_one_attached :personal_photo
	belongs_to :province, :class_name => "Province", :foreign_key => "provinces_id"

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true
	
	#fix this later...
	#canadian_postal_code = /\A[ABCEGHJKLMNPRSTVXY]{1}\\d{1}[A-Z]{1}[ -]?\\d{1}[A-Z]{1}\\d{1}\z/
	#validates :postal_code, format: { with: canadian_postal_code }
end

app/models/dreamtype.rb
class Dreamtype < ApplicationRecord

	has_many :products
	validates :horror_rating, numericality: { less_than_or_equal_to: 10,  only_integer: true }
	validates :dreamtype, presence: true

	def display_name 
		dreamtype
	end
end

app/models/order.rb
class Order < ApplicationRecord
belongs_to :customer, :class_name => "Customer", :foreign_key => "customers_id"
validates :order_date, presence: true
before_create :set_order_date
before_save :set_fulfilled 
has_many :order_details
end

def set_order_date
	self.order_date = Date.today
end

def set_fulfilled
	if self.paid_date?
		self.fulfilled = true
	end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, presence: true
  validates :product_price, presence: true
  validates :total, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
	has_one_attached :about_photo
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :dreamtype
  has_many :order_details

   mount_uploader :image, ImageUploader

  validates :description, presence: true
  validates :name, presence: true
  validates :stock, presence: true
  validates :price_per_unit, presence: true

  paginates_per 4

end

app/models/province.rb
class Province < ApplicationRecord
	has_many :customers

	validates :code, presence: true
end

app/models/shopping_bag.rb
class ShoppingBag < ApplicationRecord
  has_many :shopping_items
  
  def add_product(product_params)
    current_item = shopping_items.find_by(products_id: product_params[:product][:products_id])

    if current_item
      current_item.quantity += product_params[:product][:quantity].to_i
      current_item.save
    else
      new_item = shopping_items.create(products_id: product_params[:product][:products_id], 
                                  quantity: product_params[:product][:quantity],
                                  shopping_bag_id: self.id)
    end
      new_item
  end

  def bag_size
    size = 0
    self.shopping_items.each do |item|
      size += item.quantity
    end
    size
  end

  def total_price
    shopping_items.to_a.sum { |item| item.product.price_per_unit * item.quantity }
  end
end

app/models/shopping_item.rb
class ShoppingItem < ApplicationRecord
  belongs_to :product, :class_name => "Product", :foreign_key => "products_id"
  belongs_to :shopping_bag
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

	def register
		@codes = Province.pluck(:code)
		
		if params.include?(:first_name)
			@province_id = Province.where(code: params[:province]).pluck(:id).first

			@customer = Customer.create(first_name: params[:first_name],
				last_name: params[:last_name],
				address: params[:address],
				postal_code: params[:postal_code],
				email: params[:email],
				phone: params[:phone], 
				card_number: params[:card_number],
				password: params[:password],
				provinces_id: @province_id)

			@customer.personal_photo.attach(params[:personal_photo])

			@customer.save
			@errors = @customer.errors.full_messages

			if @customer.valid?
				session[:customer_id] = @customer.id
			#this will be change to username
			session[:customer_name] = @customer.first_name
			redirect_to products_path
		end
	end 
end

def login
	if params.include?(:email)
		@customer = Customer.where(email: params[:email], password: params[:password]).first
		if @customer
			session[:customer_id] = @customer.id
			#this will be change to username
			session[:customer_name] = @customer.first_name
			redirect_to products_path
		end

		@error = "User not found."
	end
end

def logout
	session[:customer_id] = nil
	session[:customer_name] = nil
	redirect_to products_path
	end

def outstanding

	@customer = Customer.where(id: session[:customer_id]).first

	@orders = Order.where(customers_id: session[:customer_id], fulfilled: false)
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  	@about = Page.all
  end

  def contact
  	@contact = Page.select(:contact)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dreamtypes_helper.rb
module DreamtypesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/customers/login.html.erb
<%= form_for customers_url, :url => login_post_url, :html => { :method => :post } do %>
<p>
	<%= label_tag(:email, "EMAIL:") %>
	<%= text_field_tag(:email) %>
</p>
<p>
	<%= label_tag(:password, "PASSWORD:") %>
	<%= text_field_tag(:password) %>
</p>


<% if @error %>
     <%= @error %></p>
   <% end %>

<%= submit_tag 'LOGIN', name: nil, class: "btn btn-light" %>

<div>
<%= link_to "NEW MEMBERS REGISTER HERE", register_path %>
<% end %>
</div>

app/views/customers/outstanding.html.erb
<h1>Customer Information</h1>

<% if @customer.personal_photo.attached? %>
<%= image_tag(@customer.personal_photo.variant(resize_to_limit: [200, 200])) %>
<% end %>

<div>
Name: <%= @customer.first_name %> <%= @customer.last_name %> 
</div>
<div>
Address: <%= @customer.address %>
</div>
<div>
Province: <%= @customer.province.code %>
</div>
<div>
GST: <%= @customer.province.gst %>
</div>
<div>
HST: <%= @customer.province.hst %>
</div>
<div>
PST: <%= @customer.province.pst %>
</div>

<% @orders.each do |order| %>
<h3>Order Number: <%= order.id %></h3>
<% order.order_details.each do |details| %>
				<h5>Quantity On Order: <%= details.quantity %></h5>
				<h5>Product Name: <%= details.product.name %></h5>
<% end %>
<% end %>

app/views/customers/register.html.erb
<%= form_for customers_url, :url => register_post_url, :html => { :method => :post } do |form| %>
<p>
	<%= label_tag(:email, "Email:") %>
	<%= text_field_tag(:email) %>
</p>
<p>
	<%= label_tag(:first_name, "First Name:") %>
	<%= text_field_tag(:first_name) %> 
</p>
<p>
	<%= label_tag(:last_name, "Last Name:") %>
	<%= text_field_tag(:last_name) %>

</p>
<p>
	<%= label_tag(:address, "Address:") %>
	<%= text_field_tag(:address) %>

</p>
<p>
	<%= label_tag(:last_name, "Postal Code:") %>
	<%= text_field_tag(:postal_code) %>

</p>
<p>
	<%= label_tag(:province, "Province:") %>
	<%= select_tag(:province, options_for_select(@codes))  %>
</p>
<p>
	<%= label_tag(:card_number, "Card Number:") %>
	<%= text_field_tag(:card_number) %>
</p>
<p>
	<%= label_tag(:password, "Password:") %>
	<%= text_field_tag(:password) %>
</p>

<p>
	<%= label_tag(:personal_photo, "Personal Photo:") %>
	<%= form.file_field :personal_photo,  :name => 'personal_photo' %>
</p> 

<% if @errors %>
<% @errors.each do |msg| %>

<%= @province_id %>
      <p class = "red"><%= msg %></p>
   <% end %>
<% end %>

<%= submit_tag 'Register Customer', name: nil, class: "btn btn-light" %>
<% end %>