config/routes.rb
Rails.application.routes.draw do
  resources :shopping_notes
  resources :customers
  resources :orders
  resources :shopping_items
  resources :shopping_bags
  resources :pages
  resources :dreamtypes
  resources :products
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  
  get '/about', to: 'pages#about', as: 'about'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/register', to: 'customers#register', as: 'register'
  get '/outstanding_orders', to: 'customers#outstanding', as: 'outstanding'
  get '/logout', to: 'customers#logout', as: 'logout'
  get '/checkout', to: 'shopping_bags#checkout', as: 'checkout'
  get '/login', to: 'customers#login', as: 'login'
  post '/register', to: 'customers#register', as: 'register_post'
  post '/login', to: 'customers#login', as: 'login_post'
  post '/logout', to: 'customers#logout', as: 'logout_post'
  post '/checkout', to: 'shopping_bags#checkout', as: 'checkout_post'


  root to: 'products#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product, :class_name => "Product", :foreign_key => "products_id"
  belongs_to :cart
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_one_attached :personal_photo
	belongs_to :province, :class_name => "Province", :foreign_key => "provinces_id"

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true
	
	#fix this later...
	#canadian_postal_code = /\A[ABCEGHJKLMNPRSTVXY]{1}\\d{1}[A-Z]{1}[ -]?\\d{1}[A-Z]{1}\\d{1}\z/
	#validates :postal_code, format: { with: canadian_postal_code }
end

app/models/dreamtype.rb
class Dreamtype < ApplicationRecord

	has_many :products
	validates :horror_rating, numericality: { less_than_or_equal_to: 10,  only_integer: true }
	validates :dreamtype, presence: true

	def display_name 
		dreamtype
	end
end

app/models/order.rb
class Order < ApplicationRecord
belongs_to :customer, :class_name => "Customer", :foreign_key => "customers_id"
validates :order_date, presence: true
before_create :set_order_date
before_save :set_fulfilled 
has_many :order_details
end

def set_order_date
	self.order_date = Date.today
end

def set_fulfilled
	if self.paid_date?
		self.fulfilled = true
	end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, presence: true
  validates :product_price, presence: true
  validates :total, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
	has_one_attached :about_photo
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :dreamtype
  has_many :order_details

   mount_uploader :image, ImageUploader

  validates :description, presence: true
  validates :name, presence: true
  validates :stock, presence: true
  validates :price_per_unit, presence: true

  paginates_per 4

end

app/models/province.rb
class Province < ApplicationRecord
	has_many :customers

	validates :code, presence: true
end

app/models/shopping_bag.rb
class ShoppingBag < ApplicationRecord
  has_many :shopping_items
  
  def add_product(product_params)
    current_item = shopping_items.find_by(products_id: product_params[:product][:products_id])

    if current_item
      current_item.quantity += product_params[:product][:quantity].to_i
      current_item.save
    else
      new_item = shopping_items.create(products_id: product_params[:product][:products_id], 
                                  quantity: product_params[:product][:quantity],
                                  shopping_bag_id: self.id)
    end
      new_item
  end

  def bag_size
    size = 0
    self.shopping_items.each do |item|
      size += item.quantity
    end
    size
  end

  def total_price
    shopping_items.to_a.sum { |item| item.product.price_per_unit * item.quantity }
  end
end

app/models/shopping_item.rb
class ShoppingItem < ApplicationRecord
  belongs_to :product, :class_name => "Product", :foreign_key => "products_id"
  belongs_to :shopping_bag
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  	@about = Page.all
  end

  def contact
  	@contact = Page.select(:contact)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		if params[:search]
			if (params[:category] == "")
				@products = Product.where("name LIKE ? OR Products.description LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%").page params[:page]
			end
			if (params[:category] == "AbsurdDream")
				@products = Product.joins(:dreamtype).where("dreamtype = 'AbsurdDream' AND name LIKE ? OR Products.description LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%").page params[:page]
			end
			if (params[:category] == "ComfortingDream")
				@products = Product.joins(:dreamtype).where("dreamtype = 'ComfortingDream' AND name LIKE ? OR Products.description LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%").page params[:page]
			end
		elsif params[:datefilter]
			if (params[:datefilter] == "Recently Updated")
				@products = Product.where('updated_at > ?', 2.days.ago).page params[:page]
			end
			if (params[:datefilter] == "Recently Created")
				@products = Product.where('created_at > ?', 2.days.ago).page params[:page]
			end
		else
			@products = Product.order(:name).page params[:page]
		end

		@dreamtypes = Dreamtype.pluck(:dreamtype)

	end

	def show
		@product = Product.find(params[:id])
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dreamtypes_helper.rb
module DreamtypesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<div class = "column">

	<h2><%= product.name %></h2>
	<p><%= product.description %></p>
	<p><%= image_tag product.image.url, :width => '150' unless product.image.url.nil?  %></p>
	<p><%= number_to_currency(product.price_per_unit) %> each</p>
	
<div>
    <% if product.stock.zero? %>
    		<p>0UT OF STOCK</p>
    <% else %>
      <%= form_for product, :url => shopping_items_path, :html => { :method => :post } do |f|%>
      <%= f.hidden_field :products_id, value: product.id %>
    	<%= f.number_field :quantity, value: 1, min: 1 %>
      <%= f.submit 'ADD TO BAG', class: "btn btn-dark" %>
      <% end %>
    <% end %>
</div>
	<% if show_deets %>
	<p>
		<%= link_to "VIEW DETAILS", product %>
	</p>
	<% end %>
	<% if show_back %>
	<p>
		<%= link_to "DREAMTYPE LISTING", dreamtype_path(product.dreamtype) %>
	</p>
	<p>
		<%= link_to "PRODUCTS LISTING", root_path %>
	</p>
	<% end %>

app/views/products/index.html.erb
<%= form_tag url_for(:controller => 'products', :action => 'index'), :method => 'get' do %>
<%= select_tag(:category, options_for_select(@dreamtypes), :include_blank => true)  %>
	<%= text_field_tag :search %>
  <%= submit_tag 'Search', name: nil, class: "btn btn-light" %>
<% end %>

<%= form_tag url_for(:controller => 'products', :action => 'index'), :method => 'get' do %>
<%= select_tag(:datefilter, options_for_select(["Recently Updated", "Recently Created"]), :include_blank => false)  %>
  <%= submit_tag 'Filter', name: nil, class: "btn btn-light" %>
<% end %>

<%= render partial: 'product',
	collection: @products,
	locals: {show_deets: true, show_back: false} 
%>

<div>
<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div>
<% end %>
</div>

<%= paginate @products %> 

app/views/products/show.html.erb
<%= render partial: 'product',
	object: @product,
	locals: {show_deets: false, show_back: true}
	%>