config/routes.rb
Rails.application.routes.draw do
  resources :shopping_notes
  resources :customers
  resources :orders
  resources :shopping_items
  resources :shopping_bags
  resources :pages
  resources :dreamtypes
  resources :products
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  
  get '/about', to: 'pages#about', as: 'about'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/register', to: 'customers#register', as: 'register'
  get '/outstanding_orders', to: 'customers#outstanding', as: 'outstanding'
  get '/logout', to: 'customers#logout', as: 'logout'
  get '/checkout', to: 'shopping_bags#checkout', as: 'checkout'
  get '/login', to: 'customers#login', as: 'login'
  post '/register', to: 'customers#register', as: 'register_post'
  post '/login', to: 'customers#login', as: 'login_post'
  post '/logout', to: 'customers#logout', as: 'logout_post'
  post '/checkout', to: 'shopping_bags#checkout', as: 'checkout_post'


  root to: 'products#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product, :class_name => "Product", :foreign_key => "products_id"
  belongs_to :cart
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_one_attached :personal_photo
	belongs_to :province, :class_name => "Province", :foreign_key => "provinces_id"

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true
	
	#fix this later...
	#canadian_postal_code = /\A[ABCEGHJKLMNPRSTVXY]{1}\\d{1}[A-Z]{1}[ -]?\\d{1}[A-Z]{1}\\d{1}\z/
	#validates :postal_code, format: { with: canadian_postal_code }
end

app/models/dreamtype.rb
class Dreamtype < ApplicationRecord

	has_many :products
	validates :horror_rating, numericality: { less_than_or_equal_to: 10,  only_integer: true }
	validates :dreamtype, presence: true

	def display_name 
		dreamtype
	end
end

app/models/order.rb
class Order < ApplicationRecord
belongs_to :customer, :class_name => "Customer", :foreign_key => "customers_id"
validates :order_date, presence: true
before_create :set_order_date
before_save :set_fulfilled 
has_many :order_details
end

def set_order_date
	self.order_date = Date.today
end

def set_fulfilled
	if self.paid_date?
		self.fulfilled = true
	end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, presence: true
  validates :product_price, presence: true
  validates :total, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
	has_one_attached :about_photo
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :dreamtype
  has_many :order_details

   mount_uploader :image, ImageUploader

  validates :description, presence: true
  validates :name, presence: true
  validates :stock, presence: true
  validates :price_per_unit, presence: true

  paginates_per 4

end

app/models/province.rb
class Province < ApplicationRecord
	has_many :customers

	validates :code, presence: true
end

app/models/shopping_bag.rb
class ShoppingBag < ApplicationRecord
  has_many :shopping_items
  
  def add_product(product_params)
    current_item = shopping_items.find_by(products_id: product_params[:product][:products_id])

    if current_item
      current_item.quantity += product_params[:product][:quantity].to_i
      current_item.save
    else
      new_item = shopping_items.create(products_id: product_params[:product][:products_id], 
                                  quantity: product_params[:product][:quantity],
                                  shopping_bag_id: self.id)
    end
      new_item
  end

  def bag_size
    size = 0
    self.shopping_items.each do |item|
      size += item.quantity
    end
    size
  end

  def total_price
    shopping_items.to_a.sum { |item| item.product.price_per_unit * item.quantity }
  end
end

app/models/shopping_item.rb
class ShoppingItem < ApplicationRecord
  belongs_to :product, :class_name => "Product", :foreign_key => "products_id"
  belongs_to :shopping_bag
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dreamtypes_helper.rb
module DreamtypesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/index.html.erb
 <% current_cart.cart_items.each do |item| %>
  <div id="container">
 <h2>Product Name: <%= item.product.name %></h2>
 <h3>Quantity: <%= item.quantity %></h3>
 <div id ="edit">

 	<%= form_for item, :method => :PUT do |f| %>
 	<%= f.number_field :quantity, value: item.quantity, min: 1 %>
 	<%= f.submit "Update" %>
 	<% end %>

 	<%= form_for item, :method => :DELETE do |f| %>
 	<%= f.submit "Delete" %>
 	<% end %>
 </div>
 <% end %>
</div>

<% if current_cart.total_price != 0 %>
<h4>Cart Total Before Tax: <%= number_to_currency(current_cart.total_price) %></h4>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dream Emporium</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container">
   <div class="row">
    <div class="col-xs-3">
      <nav class ="navbar">
        <p><%= link_to "About", about_path %></p>
        <p><%= link_to "Contact", contact_path %></p>
        <p><%= link_to "All Products Listing", root_path %></p>
        <p><%= link_to "All Dreamtypes Listing", dreamtypes_path %></p>
      <p><%= link_to "Shopping Cart", shopping_bags_path %></p>
         <% if !session[:customer_name] %>
      <p><%= link_to "Login", login_url %></p>
      <% else %>
      <p><%= link_to "Outstanding Orders", outstanding_url %></p>
      <p><%= link_to "Logout", logout_url %></p>
       <% end %>
      </nav>
    </div>
        <div class="col-xs-7">
      <%= yield %>
    </div>
  </div>

   <% if session[:customer_name] %>
 <p>Logged In As: <%= session[:customer_name] %></p>
 <% end %>

</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>about</h1>

<% @about.each do |content| %>
<p><%= content.about.html_safe %></p>

<%= image_tag(content.about_photo.variant(resize_to_limit: [500, 500])) if content.about_photo.attached? %>
<% end %>

app/views/pages/contact.html.erb
<h1>contact</h1>

<% @contact.each do |content| %>
<p><%= content.contact.html_safe %></p>
<% end %>